name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest test/

  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: test  # Run this job only if tests pass

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Tag Backend Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/airline-backend:latest -f backend.Dockerfile .

      - name: Build and Tag Frontend Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/airline-frontend:latest -f frontend.Dockerfile .

      - name: Push Backend Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/airline-backend:latest

      - name: Push Frontend Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/airline-frontend:latest
